server:
  port: 4900
  debug: true

program:
  match: 1
  ratioformat: "%.3f"
  processes:
    - VI,nvim,bonjour,/Users/bonjour/1231
    - IntelliJ,idea,,
    - Emacs,Emacs,,

logs:
  - system.log,0,tail -n%d /var/log/system.log | awk '$0 ~ /login/'
  - daily.out,1,/var/log/daily.out
