server:
  port: 4900
  debug: true

program:
  match: 1
  ratioformat: "%.3f"
  processes:
    - VI,nvim,bonjour,,
    - IntelliJ,idea,,#d53636de,#261e1e
    - Emacs,Emacs,,,

logs:
  - 0,tail -n%d /var/log/system.log | awk '$0 ~ /login/'
  - 1,/var/log/daily.out
